apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  namespace: kube-system
  annotations:
    zalando.org/skipper-filter: |
      oauthTokeninfoAnyKV("https://identity.zalando.com/realm", "users", "https://identity.zalando.com/realm", "services")
  labels:
    application: prometheus
spec:
  rules:
  - host: system-prometheus.{{ .Alias }}.zalan.do
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 80
