apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: prometheus
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: prometheus
      minAllowed:
        memory: {{.ConfigItems.prometheus_mem_min}}
        cpu: {{.ConfigItems.prometheus_cpu_min}}
      maxAllowed:
  {{ with $resources := autoscalingBufferSettings .Cluster }}
        # Set the max memory to max available on the Node
        memory: {{$resources.Memory}}
  {{ end }}
