apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: heapster
  namespace: kube-system
spec:
  selector:
    matchLabels:
      application: heapster
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: heapster
      maxAllowed:
        memory: 750Mi
