apiVersion: v1
kind: ConfigMap
metadata:
  name: log-watcher-config
  namespace: visibility
data:
  log-watcher.yaml: |
    scalyr_sampling_rules:
    ## Apply to the application
    #  -
    #    application: "some_application"
    #    value: '[{"container": "my-app-container", "sampling-rules":[{ "match_expression": ".", "sampling_rate": 0 }]}]'

    ## Apply to the application and component
    #  -
    #    application: "some_application"
    #    component: "some_component"
    #    value: '[{"container": "my-app-container", "sampling-rules":[{ "match_expression": "DEBUG", "sampling_rate": 0.1 }]}]'

    ## Apply to the half of the containers matched by application and component
    #  -
    #    application: "some_application"
    #    component: "some_component"
    #    probability: 0.5
    #    value: '[{"container": "my-app-container", "sampling-rules":[{ "match_expression": "INFO", "sampling_rate": 0 }]}]'

    ## Do NOT apply to any container matched by application and component
    #  -
    #    application: "some_application"
    #    component: "some_component"
    #    probability: 0
    #    value: '[{"container": "my-app-container", "sampling-rules":[{ "match_expression": "INFO", "sampling_rate": 0 }]}]'
