apiVersion: v1
kind: Secret
metadata:
  name: logging-agent
  namespace: {{if eq .ConfigItems.logging_agent_in_visibility "true"}}visibility{{else}}kube-system{{end}}
  labels:
    application: logging-agent
type: Opaque
data:
  scalyr-access-key: "{{ .ConfigItems.scalyr_access_key | base64 }}"
