apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    application: kube-proxy
    version: v1.14.4
spec:
  selector:
    matchLabels:
      application: kube-proxy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: kube-proxy
      labels:
        application: kube-proxy
        version: v1.14.4
      annotations:
        config/hash: {{"configmap.yaml" | manifestHash}}
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: kube-proxy
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      containers:
      - name: kube-proxy
        image: registry.opensource.zalan.do/teapot/kube-proxy:v1.14.4
        args:
        - --hostname-override=$(HOSTNAME_OVERRIDE)
        - --config=/config/kube-proxy.yaml
        - --v=2
        env:
        - name: HOSTNAME_OVERRIDE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 50m
            memory: 200Mi
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes/kubeconfig
          readOnly: true
        - name: etc-kube-ssl
          mountPath: /etc/kubernetes/ssl
          readOnly: true
        - name: kube-proxy-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/kubernetes/kubeconfig
      - name: etc-kube-ssl
        hostPath:
          path: /etc/kubernetes/ssl
      - name: kube-proxy-config
        configMap:
          name: kube-proxy-config
