apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: external-dns
  namespace: kube-system
  labels:
    application: external-dns
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-dns
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: external-dns
      maxAllowed:
        cpu: 50m
        memory: 100Mi
