apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
  labels:
    application: vpa-updater
    version: patched-0.3.0-master-9
    component: vpa
spec:
  replicas: 1
  selector:
    matchLabels:
      application: vpa-updater
  template:
    metadata:
      labels:
        application: vpa-updater
        version: patched-0.3.0-master-9
        component: vpa
    spec:
      serviceAccountName: system
      priorityClassName: system-cluster-critical
      containers:
      - name: updater
        image: registry.opensource.zalan.do/teapot/vpa-updater:patched-0.3.0-master-9
        args:
          - ./updater
          - --v=4
          - --stderrthreshold=info
          - --min-replicas=1
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 8080
