{{ if eq .ConfigItems.node_problem_detector_enabled "true" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: node-problem-detector-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: node-problem-detector
  namespace: kube-system
{{ end }}
