# everything defined under here will be deleted before applying the manifests
pre_apply: []

# everything defined under here will be deleted after applying the manifests
post_apply:
{{ if eq .ConfigItems.teapot_admission_controller_process_resources "true" }}
- name: limits
  namespace: default
  kind: LimitRange
{{ end }}
{{ if ne .ConfigItems.enable_ingress_template_controller "true" }}
- name: ingresstemplates.zalando.org
  kind: CustomResourceDefinition
{{ end }}
